#!/usr/bin/env python3
# -*- coding: utf-8 -*- 

arr = ['alex', 'bob', 'alice']      # list,可以包含不同类型元素, 可以定义多维
len (arr)       #arr长度
arr.append ('apple')    #在arr末位加一个元素
arr.insert (1, 'some')  #在指定位置插入一个元素
arr[1]      #访问指定位置元素
arr[-1]     #倒数第一个元素

L = (1,)        # 元组:有序列表,定义时候初始化, 不能修改, 一个元素时要加逗号与括号区分
