#!/usr/bin/env python3
# -*- coding: utf-8 -*-

' a test pickle '

__author__ = 'regina'

# 序列化(pickle): 把变量从内存中变成可存储或者可传输的过程

import pickle
d = dict(name='bob', age=20, score=88)


# 把任意对象序列化成一个bytes
a = pickle.dumps(d)		

# 把内容反序列化
b = pickle.loads (a)
print (b)

# 直接把对象序列化后写入一个file-like Object
f = open('test.txt', 'wb')
pickle.dump(d, f)
f.close()


# 把内容从file-like Object读出，并反序列化
f = open ('test.txt', 'rb')
a = pickle.load (f)
f.close()
print (a)
