#!/usr/bin/env python3
# -*- coding: utf-8 -*-

' a test OI '

__author__ = 'regina'

import os
# 操作文件和目录
os.path.abspath ('.')	# 查看当前绝对路径
os.path.join ('F:\\Python34', 'test')	# 创建新目录时，先把新目录完整路径表示出来 简单字符拼接
os.mkdir('F:\\Python34\\test')	# 创建一个目录
os.rmdir('F:\\Python34\\test')	# 删除目录
os.path.splitext ('F:\\Python34\\test')		#直接得到文件扩展名

os.path.split ('F:\\Python34\\test')	# 拆分路径
os.rename ('test.txt', 'test.py')		# 对文件重命名
os.remove ('test.py')		# 删掉文件


[x for x in os.listdir('.') if os.path.isdir(x)]	# 列出当前目录下的所有目录

# 列出当前目录下所有.py格式的文件
[x for x in os.listdir('.') if os.path.isfile(x) and os.path.splitext(x)[1] == '.py']
